### ISSUE TITLE
Allow specific pipe to ignore in overall process

### ISSUE THREAD

**Issue by nstrappazzonc** [debeando/lightflow#14]
For example in the `.yaml` file:

```yaml
pipes:
  - name: demo
    execute: echo -n "demo
    ignore: true
```
Only run this when specify pipe name in the cli args.
